---
driver:
  name: localhost

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 5
  log_level: debug
  hosts: all
  roles_path: ../

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
