---
- name: Create blackbox  container
  docker_container:
    name: blackbox_exporter
    command: -config.file=/blackbox-data/blackbox_exporter.yml
    hostname: "{{ blackbox_exporter_hostname }}"
    image: prom/blackbox-exporter
    volumes:
      - "{{ path }}/blackbox-data:/blackbox-data"
    published_ports:
      - 9115:9115
    restart_policy: always

- name: copy blackbox config file
  template: >
    src=templates/blackbox_exporter.yml.j2
    dest="{{ path }}/blackbox-data/blackbox_exporter.yml"
    owner=root
    group=root
    mode=0640
  notify:
    - "{{ blackbox_exporter_restart_handler }}"
