---
- name: install deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - jq
    - python-pip

- name: python deps
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: docker-py, state: absent }
    - { name: docker, state: present }

  when: install_mode == 'docker'
