---
- name: Create alertmanager container
  docker_container:
    name: alertmanager
    command: "{% for key in alertmanager_commandline_args %}--{{key}}={{alertmanager_commandline_args[key]}} {% endfor %}"
    hostname: "{{ alertmanager_hostname }}"
    image: "{{ alertmanager_image }}"
    volumes:
      - "{{ path }}/alertmanager:/alertmanager"
    published_ports:
      - 9093:9093
    restart_policy: always

- name: Ensure alertmanager templates directory exist
  file: >
    path="{{ path }}/alertmanager/template"
    owner=nobody
    group=nogroup
    mode=0740
    state=directory

- name: copy alertmanager config file
  template: >
    src=templates/alertmanager.yml.j2
    dest="{{ path }}/alertmanager/alertmanager.yml"
    owner=root
    group=root
    mode=0640
  notify:
    - "{{ alertmanager_restart_handler }}"

- name: copy alertmanager templates
  copy: >
    src="{{ item }}"
    dest="{{ path }}/alertmanager/template/{{ item | basename }}"
    owner=root
    group=nogroup
    mode=0640
  with_fileglob: "{{ alertmanager_template_files }}"
  notify:
    - "{{ alertmanager_restart_handler }}"
