---
- name: Create prometheus container
  docker_container:
    name: prometheus
    command: -config.file=/prometheus-data/prometheus.yml -alertmanager.url=http://{{ alertmanager_ip }}:9093 -storage.local.path=/prometheus-data/data
    hostname: "{{ prometheus_hostname }}"
    image: prom/prometheus
    volumes:
      - "{{ path }}/prometheus-data:/prometheus-data"
    published_ports:
      - 9090:9090
    restart_policy: always

- name: copy prometheus config file
  template: >
    src=templates/prometheus.yml.j2
    dest="{{ path }}/prometheus-data/prometheus.yml"
    owner=root
    group=root
    mode=0640
  notify:
    - "{{ prometheus_restart_handler }}"

- name: copy prometheus alert rules
  copy: >
    src=files/alert.rules
    dest="{{ path }}/prometheus-data/alert.rules"
    owner=root
    group=root
    mode=0640
  notify:
    - "{{ prometheus_restart_handler }}"
  when: default_alert_rules == true
